### ISSUE TITLE
add sync to disk

### ISSUE THREAD

**Issue by Delapouite** [byteclubfr/copycast#17]
even better than download zip when FS API ready.

**Comment by Delapouite** [comment]
> The File System API simulates a local file system that web apps can navigate around. You can develop apps that can read, write, and create files and directories in a **sandboxed, virtual file system**. 

https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Introduction

**Comment by naholyr** [comment]
Yeah but

> The File System API is a virtual representation of a file system
> 
> The API doesn't give you access to the local file system, nor is the sandbox really a section of the file system. Instead, it is a virtualized file system that looks like a full-fledged file system to the web app. It does not necessarily have a relationship to the local file system outside the browser. 
> 
> What this means is that a web app and a desktop app cannot share the same file at the same time. The API does not let your web app reach outside the browser to files that desktop apps can also work on. You can, however, export a file from a web app to a desktop app. For example, you can use the File API, create a blob, redirect an iframe to the blob, and invoke the download manager.

:(

I think we'll never be able to properly write to client's disk without a browser extension.

**Comment by Delapouite** [comment]
Right. That's what I meant with the emphasize in the previous comment. So sad.
