### ISSUE TITLE
The cpx commands is necessary to install it

### ISSUE THREAD

**Issue by cbonnissent** [byteclubfr/copycast#22]
copycast@3.0.0 octicons /usr/lib/node_modules/copycast
cpx 'node_modules/octicons/octicons/.' client/octicons

sh: cpx : commande introuvable

**Comment by naholyr** [comment]
Oops forgot to add it to devDependencies I guess.  Until we publish the fix you can `npm install cpx` locally

**Comment by Delapouite** [comment]
It's definitely here : https://github.com/byteclubfr/copycast/blob/master/package.json#L68

**Comment by cbonnissent** [comment]
I have executed the command npm -g copycast and npm complains about the
missing command cpx

**Comment by naholyr** [comment]
Could you tell us your versions of Windows, node and npm? I'll try to reproduce, thanks!

**Comment by naholyr** [comment]
OK nevermind, I got it… some assets are copied from dependencies at install time, dev or not. `cpx` has been moved to dependencies in freshly published version 3.1.0.

Maybe we should copy assets at publish time, we'll see if this gives us any more trouble or not.

Please tell me if `npm i -g copycast` now works for you (should install 3.1.0) :)

**Comment by cbonnissent** [comment]
It works thanks !

**Comment by naholyr** [comment]
Thanks for your report
