### ISSUE TITLE
[idea] copycast serves a git repository

### ISSUE THREAD

**Issue by naholyr** [byteclubfr/copycast#27]
Scenario: trainer creates git commits (or has prepared a git history) and trainees can grab this git history by cloning repo.

If a .git is found:
- One can `git clone $copycastURI/.git` (or any URL to define)
- One **cannot** `git push`
- One can `git commit` locally (access to local filesystem required), and anyone can `git pull` to grab those commits

**Comment by Delapouite** [comment]
https://github.com/byteclubfr/copycast/commit/e7ede06dceef53a09ea83f1f43e34ed0243c14dd
