### ISSUE TITLE
"public/idea.gif" not visible

### ISSUE THREAD

**Issue by naholyr** [byteclubfr/copycast#31]
File is not listed

* not in .gitignore (appears in git status)
* copycast restarted, still not visible
* renamed idea.txt, visible

**Comment by Delapouite** [comment]
https://github.com/byteclubfr/copycast/blob/0dacc0f32d23a0dcb47967b7ec3304f4058233b0/server/watcher.js#L35

**Comment by naholyr** [comment]
I find this choice weird now ^^ should we change it?

Le mer. 12 avr. 2017 à 22:16, Bruno Heridet <notifications@github.com> a
écrit :

**Comment by naholyr** [comment]
Duplicate #33
